services:
  # The main Indico container which runs flask
  # The same image is also used to run celery
  web: &web
    build:
      context: worker
      args:
        tag: "3.3.6"
    command: /opt/indico/run_indico.sh
    depends_on:
      - redis
      - celery
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
    ports:
      []
      # Indico is accessible either via nginx (localhost:8080 by default), or
      # directly via localhost:9090. In that case, static assets are served by flask
    volumes:
      - "archive:/opt/indico/archive" # file storage
      - "customization:/opt/indico/custom"
      - "static-files:/opt/indico/static"
      - "logs:/opt/indico/log" # logs
      - type: bind
        source: ${INDICO_CONFIG}
        target: /opt/indico/etc/indico.conf
        read_only: true
      - type: bind
        source: ${INDICO_LOGGING_CONFIG}
        target: /opt/indico/etc/logging.yaml
        read_only: true
    tmpfs:
      - /opt/indico/tmp:mode=0777
  # Indico celery
  celery: &celery
    <<: *web
    command: /opt/indico/run_celery.sh
    depends_on:
      - redis
    ports: []
  # Indico celery beat
  celery-beat:
    <<: *celery
    command: /opt/indico/run_celery.sh beat
  # Redis
  redis:
    image: redis
    volumes:
      - "redis:/data"
  # Postgres
  postgres:
    image: postgres:15-bookworm
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DATABASE=${PGDATABASE}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  # Nginx proxy
  # Indico can be accessed by default via localhost:8080
  nginx:
    image: ghcr.io/nginxinc/nginx-unprivileged:stable-alpine
    ports:
      - "${NGINX_PORT:-8080}:8080"
    depends_on:
      - web
    volumes:
      - "static-files:/opt/indico/static:ro"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"

volumes:
  postgres-data:
  archive:
  static-files:
  customization:
  logs:
  redis:
