services:
  app:
    #image: prestashop/prestashop:8
    build: .
    ports:
      - ${APP_PORT}:80
    environment:
      - PS_DEV_MODE=1
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=${URL}:${APP_PORT}
      - ADMIN_MAIL=admin@admin.com      # here is the email address of the admin,you can change it 
      - ADMIN_PASSWD=admin12345         # here is the password of the admin ,you can change it 
      - PS_FOLDER_ADMIN=webtestpilot
      - DB_SERVER=db
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root