services:
  app:
    #image: prestashop/prestashop:8
    build: .
    platform: linux/x86_64
    ports:
      - ${APP_PORT}:80
    environment:
      - PS_DEV_MODE=1
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=${APP_URL}:${APP_PORT}
      - ADMIN_MAIL=admin@admin.com      # here is the email address of the admin,you can change it 
      - ADMIN_PASSWD=admin12345         # here is the password of the admin ,you can change it 
      - PS_FOLDER_ADMIN=webtestpilot
      - DB_SERVER=db
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-purge-threads=1 --innodb-log-file-size=32M --innodb-log-buffer-size=8M --log-error-verbosity=1
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
