services:
  app:
    image: prestashop/prestashop:8
    ports:
      - ${APP_PORT}:80
    environment:
      - PS_DEV_MODE=1
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:${APP_PORT}
      - PS_FOLDER_ADMIN=webtestpilot
      - DB_SERVER=db
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root